"""Execute one SkillAge request through the checked-out SkillFlow source.

This file is a subprocess boundary.  It intentionally imports Harbor and the
official SkillFlow modules only after reading the request, so the normal
SkillAge test environment stays network- and Docker-free.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from pathlib import Path
from typing import Any


def _args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--request", type=Path, required=True)
    parser.add_argument("--result", type=Path, required=True)
    return parser.parse_args()


def _write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True, default=str) + "\n", encoding="utf-8")


def _skill_template(root: Path, skills: list[dict[str, Any]]) -> Path:
    template = root / "skill_template" / "skills"
    template.mkdir(parents=True, exist_ok=True)
    for skill in skills:
        skill_id = str(skill["skill_id"])
        # Skill IDs are generated by SkillAge and are safe path components.  A
        # defensive check prevents a request from escaping the run directory.
        if not skill_id or Path(skill_id).name != skill_id:
            raise ValueError(f"unsafe skill id: {skill_id!r}")
        directory = template / skill_id
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "SKILL.md").write_text(str(skill.get("content", "")), encoding="utf-8")
        for relative, content in (skill.get("support_files") or {}).items():
            relative_path = Path(str(relative))
            if relative_path.is_absolute() or ".." in relative_path.parts:
                raise ValueError(f"unsafe support file path: {relative!r}")
            target = directory / relative_path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(str(content), encoding="utf-8")
    return template


def _base_config(root: Path, request: dict[str, Any], template: Path) -> Path:
    # JSON is valid YAML and avoids adding a PyYAML dependency to SkillAge.
    api_key = os.environ.get("DASHSCOPE_API_KEY", "")
    config = {
        "job_name": "skillage-official-task",
        "agents": [
            {
                "import_path": "libs.harbor_noinstall_agents.agents:NoInstallQwenCode",
                "model_name": f"qwen/{request['model']}",
                "env": {
                    "DASHSCOPE_API_KEY": api_key,
                    "DASHSCOPE_BASE_URL": request["base_url"],
                },
                # The official iterative runner reads patch-model credentials
                # from agent.kwargs/env.  The bridge scrubs this generated
                # config and all trial text before returning to SkillAge.
                "kwargs": {
                    "base_url": request["base_url"],
                    "api_key": api_key,
                },
            }
        ],
        "environment": {
            "allow_internet": True,
            "force_build": False,
            "delete": False,
        },
        "orchestrator": {"type": "local", "n_concurrent_trials": 1, "quiet": False},
        "verifier": {"disable": False},
        "datasets": [],
    }
    config_path = root / "official_config.yaml"
    _write_json(config_path, config)
    return config_path


def _first_trial(job_dir: Path) -> Path:
    candidates = sorted(
        path for path in job_dir.iterdir()
        if path.is_dir() and (path / "result.json").is_file()
    )
    if not candidates:
        raise RuntimeError(f"official SkillFlow produced no completed trial under {job_dir}")
    return candidates[0]


def _reward(result: dict[str, Any], verifier: dict[str, Any]) -> float:
    verifier_result = result.get("verifier_result")
    rewards = verifier_result.get("rewards") if isinstance(verifier_result, dict) else None
    if isinstance(rewards, dict) and rewards:
        return float(next(iter(rewards.values())))
    for candidate in (verifier.get("performance"), verifier.get("reward"), result.get("reward")):
        if candidate is not None:
            return float(candidate)
    raise RuntimeError("official verifier output did not contain a reward/performance")


def _invoked_skills(trajectory: Any, skill_ids: set[str]) -> tuple[str, ...]:
    text = json.dumps(trajectory, ensure_ascii=False)
    return tuple(sorted(skill_id for skill_id in skill_ids if skill_id in text))


def _read_execution(request: dict[str, Any], trial_dir: Path, skill_dir: Path) -> dict[str, Any]:
    task = request["task"]
    result = json.loads((trial_dir / "result.json").read_text(encoding="utf-8"))
    verifier_path = trial_dir / "verifier" / "ctrf.json"
    verifier = json.loads(verifier_path.read_text(encoding="utf-8")) if verifier_path.is_file() else {}
    trajectory_path = trial_dir / "agent" / "trajectory.json"
    trajectory = json.loads(trajectory_path.read_text(encoding="utf-8")) if trajectory_path.is_file() else []
    performance = _reward(result, verifier)
    if not 0.0 <= performance <= 1.0:
        raise RuntimeError(f"verifier performance out of range: {performance}")
    patches: list[dict[str, Any]] = []
    if request["allow_skill_updates"] and skill_dir.is_dir():
        previous = {str(item["skill_id"]): item for item in request.get("skills", [])}
        for directory in sorted(path for path in skill_dir.iterdir() if path.is_dir()):
            skill_file = directory / "SKILL.md"
            if not skill_file.is_file():
                continue
            content = skill_file.read_text(encoding="utf-8")
            support: dict[str, str] = {}
            for path in sorted(directory.rglob("*")):
                if path.is_file() and path.name not in {"SKILL.md", "metadata.json"}:
                    support[path.relative_to(directory).as_posix()] = path.read_text(encoding="utf-8")
            old = previous.get(directory.name)
            if old and old.get("content") == content and old.get("support_files", {}) == support:
                continue
            patches.append({
                "skill_id": directory.name,
                "name": directory.name,
                "family_id": task["family_id"],
                "content": content,
                "support_files": support,
            })
    return {
        "task_id": task["task_id"],
        "performance": performance,
        "invoked_skill_ids": list(_invoked_skills(trajectory, {str(item["skill_id"]) for item in request.get("skills", [])})),
        "trajectory": trajectory if isinstance(trajectory, list) else [],
        "verifier_output": {**verifier, "performance": performance},
        "skill_patches": patches,
        "artifact_paths": [
            path.relative_to(trial_dir).as_posix()
            for path in sorted(trial_dir.rglob("*"))
            if path.is_file()
        ],
    }


def main() -> None:
    args = _args()
    request = json.loads(args.request.read_text(encoding="utf-8"))
    official_root = Path(request["official_root"]).resolve()
    if not official_root.is_dir():
        raise SystemExit(f"official SkillFlow root does not exist: {official_root}")
    if str(official_root) not in sys.path:
        sys.path.insert(0, str(official_root))

    task_root = Path(request["task_root"]).resolve()
    task_path = task_root / Path(request["task"]["relative_path"])
    if not task_path.is_dir():
        raise SystemExit(f"SkillFlow task does not exist: {task_path}")
    family_path = task_path.parent
    template = _skill_template(args.request.parent, request.get("skills", []))
    config_path = _base_config(args.request.parent, request, template)
    jobs_root = args.request.parent / "official_jobs"

    import iterative_shared_skills_runner as official_iterative
    from harbor import Job

    # The official group runner is retained as the warm-up implementation. It
    # normally discovers every task in a family; this scoped resolver makes the
    # request a one-task group without changing the checked-out source.
    original_resolver = official_iterative.resolve_group_task_paths
    official_iterative.resolve_group_task_paths = lambda _path, disable_verification: [task_path]
    try:
        if request["allow_skill_updates"]:
            runner_cfg = official_iterative.RunnerConfig(
                config_path=config_path,
                run_root_dir=jobs_root,
                max_parallel_groups=1,
                force_shared_env=True,
                project_template_dir=template,
                copy_task_skills=False,
                max_steps=60,
                max_obs_chars=3000,
                patch_temperature=0.2,
                patch_max_tokens=16384,
            )
            group_result = official_iterative.run_group_job(
                base_config_path=config_path,
                group_name=request["task"]["family_id"],
                dataset_path=family_path,
                runner_cfg=runner_cfg,
            )
            if not group_result.success:
                raise RuntimeError(group_result.message)
            job_dir = group_result.job_dir
            skill_dir = job_dir / "shared_skills" / request["task"]["family_id"]
        else:
            base_config = official_iterative.load_job_config(config_path)
            group_config = official_iterative.build_group_job_config(
                base_config=base_config,
                group_name=request["task"]["family_id"],
                dataset_path=family_path,
                ordered_task_paths=[task_path],
                run_root_dir=jobs_root,
                shared_skills_dir=template,
                force_shared_env=True,
                project_template_dir=template,
                copy_task_skills=False,
            )
            job = Job(config=group_config)
            asyncio.run(job.run())
            job_dir = jobs_root / (group_config.job_name or "skillage-official-task")
            skill_dir = template
        trial_dir = _first_trial(job_dir)
        _write_json(args.result, _read_execution(request, trial_dir, skill_dir))
    finally:
        official_iterative.resolve_group_task_paths = original_resolver
        # The API key is only present in the generated config and is removed
        # before control returns to SkillAge.
        try:
            config_path.unlink(missing_ok=True)
        except OSError:
            pass


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"SkillFlow bridge error: {exc}", file=sys.stderr)
        raise
